### ISSUE TITLE
OR condition

### ISSUE THREAD

**Issue by indapublic** [pluk77/SymfonySphinxBundle#10]
Hey! Thanks for your awesome library.
Have a question.
Is it possible to do OR condition? I want to find all occurrences with "foo" and "bar" for example

```
->match(["title", "content", "tag"], "foo")
->match(["title", "content", "tag"], "bar")
```

Something like that, but it works like AND condition.

Tried with `->match(["title", "content", "tag"], "foo | bar")` but not worked

**Comment by pluk77** [comment]
Its a pleasure.

I actually have some code I need to upload which allows for much more flexibility. Will try my best to do that soon...

**Comment by pluk77** [comment]
@indapublic I have pushed some new code, including an OR and a way to do more complex queries by way of a raw query which is not pre-processed.

Just note that multiple indexes are now set as an array, no longer as multiple arguments.

Let me know what you think

**Comment by pluk77** [comment]
I am closing this due to lack of feedback. I assume OR statements are working now.
